version: 2

models:
  - name: fact_sales
    description: "Table of sales facts containing information about wholesale purchases of liquor in the State of Iowa by retailers for sale to individuals since January 1, 2012. It includes details such as invoice and item number, date, store information, category, vendor details, item details, and sales metrics."
    columns:
      - name: invoice_and_item_number
        description: "Concatenated invoice and line number associated with the liquor order. Provides a unique identifier for individual liquor products included in the store order."
      - name: date
        description: "Date of the order."
      - name: store_number
        description: "Unique number assigned to the store that ordered the liquor."
      - name: category
        description: "Category code associated with the liquor ordered."
      - name: vendor_number
        description: "Vendor number of the company for the brand of liquor ordered."
      - name: item_number
        description: "Item number for the individual liquor product ordered."
      - name: pack
        description: "Number of bottles in a case for the liquor ordered."
      - name: bottle_volume_ml
        description: "Volume of each liquor bottle ordered in milliliters."
      - name: state_bottle_cost
        description: "The amount that Alcoholic Beverages Division paid for each bottle of liquor ordered."
      - name: state_bottle_retail
        description: "The amount the store paid for each bottle of liquor ordered."
      - name: bottles_sold
        description: "Number of bottles of liquor ordered by the store."
      - name: sale_dollars
        description: "Total cost of liquor order (number of bottles multiplied by the state bottle retail)."
      - name: volume_sold_liters
        description: "Total volume of liquor ordered in liters."
      - name: volume_sold_gallons
        description: "Total volume of liquor ordered in gallons."

  - name: dim_item
    description: "Dimension table containing information about individual liquor items ordered."
    columns:
      - name: item_number
        description: "Item number for the individual liquor product."
      - name: item_description
        description: "Description of the individual liquor product."

  - name: dim_vendor
    description: "Dimension table containing information about liquor vendors."
    columns:
      - name: vendor_number
        description: "Vendor number of the company for the brand of liquor."
      - name: vendor_name
        description: "Vendor name of the company for the brand of liquor."

  - name: dim_store
    description: "Dimension table containing information about stores."
    columns:
      - name: store_number
        description: "Unique number assigned to the store."
      - name: store_name
        description: "Name of the store."
      - name: address
        description: "Address of the store."
      - name: city
        description: "City where the store is located."
      - name: zip_code
        description: "Zip code where the store is located."
      - name: county_number
        description: "Iowa county number for the county where the store is located."
      - name: county
        description: "County where the store is located."

  - name: dim_date
    description: "Dimension table containing date information."
    columns:
      - name: date
        description: "Date."
      - name: year
        description: "Year extracted from the date."
      - name: quarter
        description: "Quarter extracted from the date."
      - name: month
        description: "Month extracted from the date."
      - name: day
        description: "Day extracted from the date."
      - name: day_of_week
        description: "Day of the week extracted from the date."

  - name: dim_category
    description: "Dimension table containing information about liquor categories."
    columns:
      - name: category
        description: "Category code associated with the liquor."
      - name: category_name
        description: "Name of the category of the liquor."
